name = "ada"
description = "guessing game"
version = "0.1.0-dev"

authors = ["Mira Ciel Nekomimi-Sireneva"]
maintainers = ["Mira Ciel Nekomimi-Sireneva <miranekomimisireneva@gmail.com>"]
maintainers-logins = ["miraneko"]
licenses = "MIT"
website = ""
tags = []

executables = ["guessing_game"]
